import { createUseStyles, type Theme } from '~/provider/theme';

export const useStyle = createUseStyles((theme: Theme) => ({
  root: {
    borderRadius: theme.radius.md,
    '&$horizontal': {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'start',
      gap: theme.space.md,
      backgroundColor: theme.color.bg.cardHeader,
      '& $label': {
        marginTop: theme.space.md,
        marginLeft: theme.space.sm,
        minWidth: '6rem',
        textAlign: 'right',
      },
      '& $triggerWrapper': { flexGrow: 1 },
    },
    '&$vertical': {
      display: 'flex',
      flexDirection: 'column',
      gap: theme.space.xs,
      backgroundColor: theme.color.bg.cardHeader,
      '& $label': {
        marginTop: theme.space.xs,
        marginLeft: theme.space.md,
      },
      '& $triggerWrapper': { flexGrow: 1 },
    },
    '&$inline': {
      display: 'inline-flex',
      alignItems: 'baseline',
      gap: theme.space.md,
    },
  },
  label: { ...theme.recipe.label },
  triggerWrapper: {
    position: 'relative',
  },
  trigger: {
    ...theme.recipe.input,
    display: 'flex',
    alignItems: 'center',
    gap: theme.space.md,
    cursor: 'pointer',
    userSelect: 'none',
    '-webkit-user-select': 'none',
    '&:focus, &:focus-within': { borderColor: theme.color.border.focus },
    '&$loading': {
      cursor: 'default',
      borderColor: '#e6e6e6',
      color: theme.color.text.muted,
      '&:hover': { borderColor: '#e6e6e6' },
      '&:focus, &:focus-within': { borderColor: '#e6e6e6' },
    },
    '&$disabled': {
      cursor: 'not-allowed',
      '&:hover': { borderColor: theme.color.border.default },
      '&:focus, &:focus-within': { borderColor: theme.color.border.default },
    },
  },
  triggerText: {
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '0.80rem',
    color: theme.color.text.primary,
    '&$placeholder': { color: theme.color.text.faint },
  },
  searchInput: {
    border: 'none',
    outline: 'none',
    background: 'transparent',
    fontFamily: theme.fontFamily.body,
    fontSize: '0.80rem',
    color: theme.color.text.primary,
    flex: 1,
    minWidth: 0,
    padding: 0,
    '&::placeholder': { color: theme.color.text.faint },
  },
  clearButton: {
    display: 'flex',
    alignItems: 'center',
    color: theme.color.text.faint,
    cursor: 'pointer',
    flexShrink: 0,
    '&:hover': { color: theme.color.text.primary },
  },
  chevron: {
    display: 'flex',
    alignItems: 'center',
    flexShrink: 0,
    color: theme.color.text.faint,
    transform: 'rotate(90deg)',
    transition: `transform ${theme.transition.fast}`,
    '&$open': { transform: 'rotate(-90deg)' },
  },
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: theme.space.xxs,
    zIndex: theme.zIndex.sticky,
    border: `1px solid ${theme.color.border.strong}`,
    borderRadius: theme.radius.md,
    backgroundColor: theme.color.bg.card,
    boxShadow: theme.shadow.hoverLift,
    overflow: 'hidden',
  },
  optionList: {
    listStyle: 'none',
    margin: 0,
    padding: `${theme.space.xs} 0`,
    maxHeight: '12.5rem',
    overflowY: 'auto',
  },
  option: {
    fontFamily: theme.fontFamily.body,
    fontSize: '0.80rem',
    padding: `${theme.space.md} ${theme.space.xxl}`,
    cursor: 'pointer',
    color: theme.color.text.primary,
    '&:hover': { backgroundColor: theme.color.bg.cardHeader },
    '&$highlighted': { backgroundColor: theme.color.brand.light },
    '&$selected': { fontWeight: theme.fontWeight.semibold },
    '&$emptyOption': {
      color: theme.color.text.faint,
      fontStyle: 'italic',
      cursor: 'default',
      '&:hover': { backgroundColor: 'transparent' },
    },
  },
  matchHighlight: {
    backgroundColor: theme.color.blue[100],
    borderRadius: theme.radius.sm,
    padding: '0 1px',
  },
  spinner: { ...theme.recipe.spinner },
  // Empty modifier classes — referenced as $name in compound selectors above
  loading: {},
  disabled: { opacity: 0.5 },
  open: {},
  placeholder: {},
  highlighted: {},
  selected: {},
  emptyOption: {},
  // Layout variant classes
  horizontal: {},
  vertical: {},
  inline: {},
}));
