import { createUseStyles, type Theme } from '~/provider/theme';

export const useStyle = createUseStyles((theme: Theme) => ({
  root: {
    background: theme.colors.bg.card,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.borderRadius.md,
    padding: '0.625rem 0.75rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.625rem',
  },
  rootError: {
    background: theme.colors.bg.card,
    border: `1px solid ${theme.colors.danger}`,
    borderRadius: theme.borderRadius.md,
    padding: '0.625rem 0.75rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.625rem',
  },
  iconWrapperQueued: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    background: theme.colors.borderLight,
    color: theme.colors.text.muted,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  iconWrapperUploading: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    background: theme.colors.primaryLight,
    color: theme.colors.primaryHover,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  iconWrapperDone: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    background: '#dcfce7',
    color: theme.colors.success,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  iconWrapperError: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    background: '#fee2e2',
    color: theme.colors.danger,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  content: {
    flex: 1,
    minWidth: 0,
  },
  filename: {
    fontSize: theme.text.size.md,
    color: theme.colors.text.primary,
    fontWeight: 500,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  progressRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
    marginTop: '0.25rem',
  },
  barTrack: {
    flex: 1,
    height: 4,
    background: theme.colors.borderLight,
    borderRadius: 2,
    overflow: 'hidden',
  },
  barFillQueued: {
    height: '100%',
    borderRadius: 2,
    width: '0%',
  },
  barFillUploading: {
    height: '100%',
    borderRadius: 2,
    background: theme.colors.primary,
    transition: 'width 0.1s ease',
  },
  barFillDone: {
    height: '100%',
    borderRadius: 2,
    background: theme.colors.success,
  },
  barFillError: {
    height: '100%',
    borderRadius: 2,
    background: theme.colors.danger,
  },
  label: {
    fontSize: theme.text.size.sm,
    color: theme.colors.text.faint,
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  labelDone: {
    fontSize: theme.text.size.sm,
    color: theme.colors.success,
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  labelError: {
    fontSize: theme.text.size.sm,
    color: theme.colors.danger,
    whiteSpace: 'nowrap',
    flexShrink: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '12rem',
  },
}));
