import { createUseStyles } from '../../provider/theme';
import type { Theme } from '../../provider/theme';
import { applyTransparency } from '../../utils';

export const useStyle = createUseStyles((theme: Theme) => ({
  root: {
    background: applyTransparency(theme.colors.bg.page, 0.5),
    color: '#111111',
    padding: '1rem 1.5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: '0px',
    backdropFilter: 'blur(10px) saturate(0%)',
    zIndex: 1000,
  },
  title: {
    fontSize: '1.25rem',
    display: 'flex',
    alignItems: 'center',
    gap: '.5rem',
    top: '-1px',
    position: 'relative',
    zIndex: 10,
  },
  navigation: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '1rem',
    width: '100vw',
    height: '65px',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  navigationItem: {
    gap: '0.5em',
    color: '#111111FF',
    textDecoration: 'none',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '0.80rem',
    userSelect: 'none',
    '-webkit-user-select': 'none',
    transitionProperty: 'color, border-bottom-color',
    transitionDuration: '0.1s',
    transitionTimingFunction: 'ease-in',
    borderBottomStyle: 'solid',
    borderBottomWidth: '2px',
    borderBottomColor: 'transparent',
    cursor: 'pointer',
    display: 'inline-flex',
    borderStyle: 'none',
    outlineStyle: 'none',
    paddingBottom: '4px',
    marginTop: '6px',
    '&:hover': {
      transitionDuration: '0s',
      color: '#11111177',
    },
    '&$active': {
      color: '#111111FF',
      borderBottomColor: '#111111',
    },
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    gap: '.75rem',
    position: 'relative',
    zIndex: 10,
  },
  username: {
    fontSize: '.875rem',
    opacity: 0.85,
  },
  active: {},
}));
