import { createUseStyles } from 'react-jss';
import type { Theme } from '../../theme/theme';

export const useStyle = createUseStyles((theme: Theme) => ({
  root: {
    maxWidth: 680,
    margin: '0 auto',
    padding: '1rem',
  },
  loading: {
    color: theme.colors.text.muted,
    padding: '2rem',
    textAlign: 'center',
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  heading: {
    flex: 1,
    margin: 0,
    fontSize: '1.25rem',
    color: theme.colors.text.primary,
  },
  cancelBtn: {
    background: 'none',
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.borderRadius.sm,
    color: theme.colors.text.secondary,
    cursor: 'pointer',
    padding: '0.375rem 0.75rem',
    fontSize: '0.875rem',
    '&:hover': { background: theme.colors.bg.page },
  },
  saveBtn: {
    background: theme.colors.primary,
    border: 'none',
    borderRadius: theme.borderRadius.sm,
    color: '#fff',
    cursor: 'pointer',
    padding: '0.375rem 0.75rem',
    fontSize: '0.875rem',
    '&:hover': { background: theme.colors.primaryHover },
    '&:disabled': { opacity: 0.6, cursor: 'default' },
  },
  error: {
    color: theme.colors.danger,
    fontSize: '0.875rem',
    marginBottom: '1rem',
  },
  form: {
    display: 'grid',
    gridTemplateColumns: '140px 1fr',
    gap: '0.75rem 1rem',
    alignItems: 'start',
  },
  label: {
    fontWeight: 600,
    fontSize: '0.875rem',
    color: theme.colors.text.secondary,
    paddingTop: '0.5rem',
  },
  input: {
    width: '100%',
    padding: '0.375rem 0.625rem',
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.borderRadius.sm,
    fontSize: '0.875rem',
    color: theme.colors.text.primary,
    background: theme.colors.bg.input,
    boxSizing: 'border-box',
    '&:focus': {
      outline: 'none',
      borderColor: theme.colors.primary,
    },
  },
  textarea: {
    width: '100%',
    padding: '0.375rem 0.625rem',
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.borderRadius.sm,
    fontSize: '0.875rem',
    color: theme.colors.text.primary,
    background: theme.colors.bg.input,
    boxSizing: 'border-box',
    resize: 'vertical',
    '&:focus': {
      outline: 'none',
      borderColor: theme.colors.primary,
    },
  },
  identifierSection: {
    gridColumn: '1 / -1',
  },
  identifierHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    marginBottom: '0.5rem',
  },
  identifierRow: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '0.375rem',
    alignItems: 'center',
  },
  addBtn: {
    background: 'none',
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.borderRadius.sm,
    color: theme.colors.primary,
    cursor: 'pointer',
    fontSize: '0.8rem',
    padding: '0.125rem 0.5rem',
  },
  removeBtn: {
    background: 'none',
    border: 'none',
    color: theme.colors.danger,
    cursor: 'pointer',
    fontSize: '1rem',
    padding: '0 0.25rem',
    flexShrink: 0,
  },
}));
