import { createUseStyles, type Theme } from '~/provider/theme';

export const useStyle = createUseStyles((theme: Theme) => ({
  root: {
    background: theme.color.bg.input,
    border: `1px solid ${theme.color.border.default}`,
    borderRadius: theme.radius.lg,
    position: 'relative',
    boxShadow: theme.shadow.cardStack,
    '&:hover': { borderColor: theme.color.border.hover },
    '&$focused': { borderColor: theme.color.border.focus },
  },
  focused: {},
  chipsRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.space.sm,
    padding: theme.space.md,
  },
  divider: {
    height: '1px',
    background: theme.color.border.strong,
    margin: `0 ${theme.space.md}`,
  },
  inputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.space.md,
    padding: `${theme.space.sm} ${theme.space.lg}`,
  },
  searchIcon: {
    color: theme.color.text.faint,
    flexShrink: 0,
  },
  clearButton: {
    '&&': {
      borderRadius: '50%',
      padding: theme.space.xxxs,
      color: theme.color.text.primary,
      flexShrink: 0,
      marginRight: `-${theme.space.xxs}`,
      '&:hover': {
        backgroundColor: theme.color.danger.light,
        color: theme.color.text.primary,
      },
      '&:active': {
        backgroundColor: theme.color.danger.light,
        filter: 'brightness(0.92)',
        color: theme.color.text.primary,
      },
    },
  },
  input: {
    flex: 1,
    background: 'none',
    border: 'none',
    outline: 'none',
    color: theme.color.text.primary,
    fontSize: theme.fontSize.md,
    lineHeight: theme.lineHeight.body,
    fontFamily: theme.fontFamily.body,
    '&::placeholder': { color: theme.color.text.faint },
    '&::-webkit-search-cancel-button': { '-webkit-appearance': 'none' },
    [theme.breakpoint.mobile]: { fontSize: '1rem' },
  },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.space.xs,
    padding: `${theme.space.xs} ${theme.space.md} ${theme.space.xs} ${theme.space.sm}`,
    borderRadius: theme.radius.md,
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.medium,
    whiteSpace: 'nowrap',
    border: '1px solid transparent',
  },
  chipTypeLabel: {
    fontSize: theme.fontSize.xxs,
    fontWeight: theme.fontWeight.bold,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    opacity: 0.65,
    marginRight: '1px',
  },
  chipRemove: {
    opacity: 0.4,
    fontSize: theme.fontSize.xxs,
    marginLeft: theme.space.xs,
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
    lineHeight: 1,
    color: 'inherit',
    '&:hover': { opacity: 0.8 },
  },
  chipStatus: {
    color: theme.color.chip.status.text,
    background: theme.color.chip.status.bg,
    borderColor: theme.color.chip.status.border,
  },
  chipAuthor: {
    color: theme.color.chip.author.text,
    background: theme.color.chip.author.bg,
    borderColor: theme.color.chip.author.border,
  },
  chipSeries: {
    color: theme.color.chip.series.text,
    background: theme.color.chip.series.bg,
    borderColor: theme.color.chip.series.border,
  },
  chipSubject: {
    color: theme.color.chip.subject.text,
    background: theme.color.chip.subject.bg,
    borderColor: theme.color.chip.subject.border,
  },
  chipEntryType: {
    color: theme.color.chip.entryType.text,
    background: theme.color.chip.entryType.bg,
    borderColor: theme.color.chip.entryType.border,
  },
  '@keyframes spin': {
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(360deg)' },
  },
  searchSpinner: {
    width: 18,
    height: 18,
    border: `2px solid ${theme.color.border.default}`,
    borderTopColor: theme.color.text.faint,
    borderRadius: '50%',
    animation: '$spin 0.6s linear infinite',
    flexShrink: 0,
  },
  dropdown: {
    position: 'absolute',
    top: 'calc(100% + 4px)',
    left: 0,
    right: 0,
    zIndex: theme.zIndex.sticky,
    background: theme.color.bg.card,
    border: `1px solid ${theme.color.border.default}`,
    borderRadius: theme.radius.md,
    boxShadow: theme.shadow.hoverLift,
    overflow: 'hidden',
  },
  dropdownGroup: {
    padding: `${theme.space.xs} 0`,
    '& + &': { borderTop: `1px solid ${theme.color.border.strong}` },
  },
  dropdownGroupLabel: {
    padding: `${theme.space.xs} ${theme.space.xxl} ${theme.space.xxxs}`,
    fontSize: theme.fontSize.xxs,
    fontWeight: theme.fontWeight.bold,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: theme.color.text.faint,
  },
  dropdownItem: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.space.md,
    padding: `${theme.space.lg} ${theme.space.xxl}`,
    fontSize: theme.fontSize.sm,
    color: theme.color.text.primary,
    cursor: 'pointer',
    '&:hover, &$dropdownItemHighlighted': { background: theme.color.bg.cardHeader },
  },
  dropdownItemHighlighted: {},
  dropdownItemType: {
    fontSize: theme.fontSize.xxs,
    padding: `1px ${theme.space.sm}`,
    borderRadius: theme.radius.sm,
    fontWeight: theme.fontWeight.bold,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    flexShrink: 0,
  },
  dropdownItemTypeStatus: {
    color: theme.color.chip.status.text,
    background: theme.color.chip.status.bg,
  },
  dropdownItemTypeAuthor: {
    color: theme.color.chip.author.text,
    background: theme.color.chip.author.bg,
  },
  dropdownItemTypeSeries: {
    color: theme.color.chip.series.text,
    background: theme.color.chip.series.bg,
  },
  dropdownItemTypeBook: {
    color: theme.color.chip.book.text,
    background: theme.color.chip.book.bg,
  },
  dropdownItemTypeSubject: {
    color: theme.color.chip.subject.text,
    background: theme.color.chip.subject.bg,
  },
  dropdownItemTypeEntryType: {
    color: theme.color.chip.entryType.text,
    background: theme.color.chip.entryType.bg,
  },
  dropdownItemText: { flex: 1, minWidth: 0 },
  dropdownItemMatch: { fontWeight: theme.fontWeight.bold },
  dropdownItemAdditive: {
    marginLeft: 'auto',
    fontSize: theme.fontSize.xxs,
    fontWeight: theme.fontWeight.bold,
    color: theme.color.chip.subject.text,
    opacity: 0.7,
  },
}));
