import { createUseStyles, Theme } from '~/provider/theme';

export const useStyle = createUseStyles((theme: Theme) => ({
  root: {
    position: 'relative',
  },
  chipsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: theme.space.xs,
    padding: theme.space.xs,
    backgroundColor: theme.color.bg.input,
    border: `1px solid ${theme.color.border.default}`,
    borderRadius: theme.radius.md,
    cursor: 'text',
    minHeight: '2.25rem',
    '&:focus-within': {
      borderColor: theme.color.border.focus,
    },
  },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: theme.space.xxs,
    padding: `${theme.space.xxs} ${theme.space.sm}`,
    backgroundColor: theme.color.brand.light,
    borderRadius: theme.radius.sm,
    fontSize: theme.fontSize.sm,
    color: theme.color.text.primary,
    lineHeight: theme.lineHeight.tight,
  },
  chipRemove: {
    display: 'flex',
    alignItems: 'center',
    background: 'none',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    color: theme.color.text.muted,
    fontSize: theme.fontSize.md,
    lineHeight: 1,
    '&:hover': {
      color: theme.color.danger.default,
    },
  },
  input: {
    border: 'none',
    outline: 'none',
    background: 'transparent',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    color: theme.color.text.primary,
    flexGrow: 1,
    minWidth: '8rem',
    padding: `${theme.space.xxs} ${theme.space.xs}`,
  },
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    marginTop: theme.space.xxs,
    padding: 0,
    listStyle: 'none',
    backgroundColor: theme.color.bg.input,
    border: `1px solid ${theme.color.border.default}`,
    borderRadius: theme.radius.md,
    boxShadow: theme.shadow.hoverLift,
    zIndex: theme.zIndex.sticky,
    maxHeight: '12rem',
    overflowY: 'auto',
  },
  dropdownItem: {
    padding: `${theme.space.md} ${theme.space.xl}`,
    cursor: 'pointer',
    fontSize: theme.fontSize.md,
    color: theme.color.text.primary,
    '&:hover': {
      backgroundColor: theme.color.bg.cardHeader,
    },
    '&$highlighted': {
      backgroundColor: theme.color.brand.light,
    },
  },
  highlighted: {},
}));
